meta:
  url:
  title:
  description:
  siteName:
slide:
  loop: false
  ui:
    sidebar: true
    pagination: bullets
  code:
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
